# Generated by Django 2.1.5 on 2019-01-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CedhResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('MOD', 'Modern'), ('LEG', 'Legacy'), ('CEDH', 'Competitive EDH')], max_length=5)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('MOD', 'Modern'), ('LEG', 'Legacy'), ('CEDH', 'Competitive EDH')], max_length=5)),
                ('date_started', models.DateField()),
                ('number_of_events', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_wins', models.PositiveSmallIntegerField(null=True)),
                ('p2_wins', models.PositiveSmallIntegerField(null=True)),
                ('draws', models.PositiveSmallIntegerField(null=True)),
                ('outcome', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('dci', models.IntegerField(primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('nickname', models.CharField(default=None, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Event')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1', to='app.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2', to='app.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Round'),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.League'),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player'),
        ),
        migrations.AddField(
            model_name='cedhresult',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.League'),
        ),
        migrations.AddField(
            model_name='cedhresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player'),
        ),
    ]
