# Generated by Django 2.1.5 on 2019-01-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190124_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('LEG', 'Legacy'), ('CEDH', 'Competitive EDH'), ('MOD', 'Modern')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('LEG', 'Legacy'), ('CEDH', 'Competitive EDH'), ('MOD', 'Modern')], max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='dci',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
