# Generated by Django 2.1.5 on 2019-01-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190124_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('MOD', 'Modern'), ('LEG', 'Legacy'), ('CEDH', 'Competitive EDH')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('MOD', 'Modern'), ('LEG', 'Legacy'), ('CEDH', 'Competitive EDH')], max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
