# Generated by Django 2.1.5 on 2019-01-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190124_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedhresult',
            name='played_both',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('MOD', 'Modern'), ('CEDH', 'Competitive EDH'), ('LEG', 'Legacy')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('MOD', 'Modern'), ('CEDH', 'Competitive EDH'), ('LEG', 'Legacy')], max_length=5),
        ),
    ]
