# Generated by Django 2.1.5 on 2019-01-27 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190126_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedhresult',
            name='standing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='draws',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='standing',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='wins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cedhresult',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 26)),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('CEDH', 'Competitive EDH'), ('LEG', 'Legacy'), ('MOD', 'Modern')], max_length=5),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('CEDH', 'Competitive EDH'), ('LEG', 'Legacy'), ('MOD', 'Modern')], max_length=5),
        ),
    ]
