# Generated by Django 2.1.5 on 2019-01-27 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190126_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresult',
            name='was_here',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cedhresult',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 27)),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('MOD', 'Modern'), ('CEDH', 'Competitive EDH'), ('LEG', 'Legacy')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('MOD', 'Modern'), ('CEDH', 'Competitive EDH'), ('LEG', 'Legacy')], max_length=5),
        ),
    ]
