# Generated by Django 2.1.5 on 2019-01-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190127_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('LEG', 'Legacy'), ('CEDH', 'Competitive EDH'), ('MOD', 'Modern')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('LEG', 'Legacy'), ('CEDH', 'Competitive EDH'), ('MOD', 'Modern')], max_length=5),
        ),
    ]
