# Generated by Django 2.1.5 on 2019-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190127_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='cedhresult',
            name='was_here',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cedhresult',
            name='date',
            field=models.DateField(default='2019-01-31'),
        ),
        migrations.AlterField(
            model_name='cedhresult',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('CEDH', 'Competitive EDH'), ('LEG', 'Legacy'), ('MOD', 'Modern')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('CEDH', 'Competitive EDH'), ('LEG', 'Legacy'), ('MOD', 'Modern')], max_length=5),
        ),
    ]
