# Generated by Django 2.1.5 on 2019-01-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190128_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('MOD', 'Modern'), ('LEG', 'Legacy'), ('CEDH', 'Competitive EDH')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('MOD', 'Modern'), ('LEG', 'Legacy'), ('CEDH', 'Competitive EDH')], max_length=5),
        ),
    ]
