# Generated by Django 2.1.5 on 2019-05-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190128_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='url',
            field=models.CharField(default='fix-me', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('LEG', 'Legacy'), ('STD', 'Standard'), ('MOD', 'Modern'), ('CEDH', 'Competitive EDH')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('LEG', 'Legacy'), ('STD', 'Standard'), ('MOD', 'Modern'), ('CEDH', 'Competitive EDH')], max_length=5),
        ),
    ]
