# Generated by Django 2.1.5 on 2019-05-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190505_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='url',
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('CEDH', 'Competitive EDH'), ('STD', 'Standard'), ('LEG', 'Legacy'), ('MOD', 'Modern')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('CEDH', 'Competitive EDH'), ('STD', 'Standard'), ('LEG', 'Legacy'), ('MOD', 'Modern')], max_length=5),
        ),
    ]
