# Generated by Django 2.0.7 on 2018-08-03 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='format',
        ),
        migrations.RemoveField(
            model_name='league',
            name='format',
        ),
        migrations.RemoveField(
            model_name='leagueresult',
            name='event',
        ),
        migrations.RemoveField(
            model_name='leagueresult',
            name='player',
        ),
        migrations.RemoveField(
            model_name='round',
            name='event',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='LeagueResult',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='leagues.EventRecord'),
            preserve_default=False,
        ),
    ]
