# Generated by Django 2.0.7 on 2018-08-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20180802_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='data',
            field=models.FileField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrecord',
            name='format',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='draws',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='opp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent', to='leagues.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='oppwins',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='outcome',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='pwins',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='roundNumber',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='dci',
            field=models.CharField(default=None, max_length=15, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='first',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
