# Generated by Django 2.0.7 on 2018-08-03 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20180802_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='opp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_p2', to='leagues.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_p1', to='leagues.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
