# Generated by Django 2.0.7 on 2018-08-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20180802_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='draws',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='oppwins',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='pwins',
            field=models.SmallIntegerField(null=True),
        ),
    ]
