# Generated by Django 2.0.7 on 2018-08-03 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_auto_20180802_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='opp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leagues.Player'),
        ),
    ]
