# Generated by Django 2.0.7 on 2018-08-03 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_auto_20180802_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.SmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.EventRecord')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Player')),
            ],
        ),
    ]
