# Generated by Django 2.0.7 on 2018-08-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_standingsrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dci',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
