# Generated by Django 2.0.7 on 2018-08-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_auto_20180803_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingsrecord',
            name='points',
            field=models.SmallIntegerField(default=0),
        ),
    ]
