# Generated by Django 2.0.7 on 2018-08-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_standingsrecord_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
