# Generated by Django 2.1.5 on 2019-01-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_auto_20180803_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='CedhResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('CEDH', 'Competitive EDH'), ('LEG', 'Legacy'), ('MOD', 'Modern')], max_length=5)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Event')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('CEDH', 'Competitive EDH'), ('LEG', 'Legacy'), ('MOD', 'Modern')], max_length=5)),
                ('date_started', models.DateField()),
                ('number_of_events', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Event')),
            ],
        ),
        migrations.RemoveField(
            model_name='standingsrecord',
            name='event',
        ),
        migrations.RemoveField(
            model_name='standingsrecord',
            name='player',
        ),
        migrations.RemoveField(
            model_name='match',
            name='event',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opp',
        ),
        migrations.RemoveField(
            model_name='match',
            name='oppwins',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player',
        ),
        migrations.RemoveField(
            model_name='match',
            name='pwins',
        ),
        migrations.RemoveField(
            model_name='match',
            name='roundNumber',
        ),
        migrations.AddField(
            model_name='match',
            name='p1_wins',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_wins',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1', to='leagues.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2', to='leagues.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='draws',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='outcome',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.DeleteModel(
            name='EventRecord',
        ),
        migrations.DeleteModel(
            name='StandingsRecord',
        ),
        migrations.AddField(
            model_name='eventresult',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
        ),
        migrations.AddField(
            model_name='eventresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Player'),
        ),
        migrations.AddField(
            model_name='cedhresult',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League'),
        ),
        migrations.AddField(
            model_name='cedhresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='leagues.Round'),
            preserve_default=False,
        ),
    ]
