# Generated by Django 2.1.5 on 2019-01-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_auto_20190121_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('CEDH', 'Competitive EDH'), ('MOD', 'Modern'), ('LEG', 'Legacy')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('CEDH', 'Competitive EDH'), ('MOD', 'Modern'), ('LEG', 'Legacy')], max_length=5),
        ),
    ]
