# Generated by Django 2.1.5 on 2019-01-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_auto_20190123_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('MOD', 'Modern'), ('LEG', 'Legacy'), ('CEDH', 'Competitive EDH')], max_length=5),
        ),
        migrations.AlterField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('MOD', 'Modern'), ('LEG', 'Legacy'), ('CEDH', 'Competitive EDH')], max_length=5),
        ),
    ]
